services:
  # 1. The FastAPI Backend
  - type: web
    name: store-intel-api
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: store-intel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: store-intel-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: store-intel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: store-intel-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: store-intel-db
          property: database

  # 2. The Live Dashboard (Static Site)
  - type: web
    name: store-intel-dashboard
    env: static
    plan: free
    staticPublishPath: ./dashboard

databases:
  # 3. The PostgreSQL Database
  - name: store-intel-db
    plan: free
    region: oregon
